NUMPY PART-1

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
np.array(l)

array([1, 2, 3, 4])

In [4]:
ar = np.array(l)

In [5]:
ar                           # one dimentional array

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])               # Two dimentional array

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)                  # Matrix is a Two dimentional array

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
a = np.array(l)

In [15]:
a

array([1, 2, 3, 4])

In [16]:
c = a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
c[0]=100

In [19]:
c

array([100,   2,   3,   4])

In [20]:
d = np.copy(a)

In [21]:
a

array([100,   2,   3,   4])

In [22]:
a[1]= 400

In [23]:
a

array([100, 400,   3,   4])

In [24]:
np.fromfunction(lambda i, j : i==j , (3,3) )

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
np.fromfunction(lambda i, j : i*j , (3,3) )

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
np.fromfunction(lambda i, j : i+j , (3,3) )

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [30]:
np.fromfunction(lambda i, j : i-j, (4,4))

array([[ 0., -1., -2., -3.],
       [ 1.,  0., -1., -2.],
       [ 2.,  1.,  0., -1.],
       [ 3.,  2.,  1.,  0.]])

In [32]:
np.fromfunction(lambda i,j : i/j , (5,5))

/tmp/ipykernel_165/1572750834.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j : i/j , (5,5))
/tmp/ipykernel_165/1572750834.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j : i/j , (5,5))


array([[       nan, 0.        , 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 2.        , 1.        , 0.66666667, 0.5       ],
       [       inf, 3.        , 1.5       , 1.        , 0.75      ],
       [       inf, 4.        , 2.        , 1.33333333, 1.        ]])

In [34]:
 iterable = ( i*i for i in range(5))

In [35]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [46]:
np.fromstring('4 ,5' , sep= ', ')

array([4., 5.])

In [47]:
#Numpy - Data Types.

In [48]:
l =[1,2,3,4,5,6]

In [50]:
ar =  np.array(l)

In [51]:
ar

array([1, 2, 3, 4, 5, 6])

In [52]:
ar.ndim

1

In [55]:
ar2 = np.array([[1,2,3,4] , [5,6,7,8,]])

In [56]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
p = [1,2,3,4,5]

In [59]:
ar= np.array(p)

In [60]:
ar

array([1, 2, 3, 4, 5])

In [77]:
p1 = ([[1,2,3,4,5] , [4,5,6,78,9], [2,3,5,6,6], [4,5,6,7,8], [5,6,7,8,9]])

In [78]:
ar = np.array(p1)

In [79]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6, 78,  9],
       [ 2,  3,  5,  6,  6],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9]])

In [69]:
ar.ndim

2

In [70]:
ar.size

25

In [74]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6, 78,  9],
       [ 2,  3,  5,  6,  6],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9]])

In [75]:
ar.shape

(5, 5)

In [82]:
ar.dtype

dtype('int64')

In [83]:
ar2.dtype

dtype('int64')

In [84]:
ar22 = np.array([(1.4,45,45),(23,65,64)])

In [85]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 65. , 64. ]])

In [86]:
ar22.shape

(2, 3)

In [87]:
ar22.dtype

dtype('float64')

In [95]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [102]:
list(np.arange(2.3 , 4.6, .3))

TypeError: 'range' object is not callable

In [104]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [105]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [107]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [110]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [111]:
np.ones(4)

array([1., 1., 1., 1.])

In [115]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [117]:
on =np.ones((2,3,4))

In [118]:
on +5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [119]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [120]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [122]:
np.logspace(2,5 , 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [124]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [125]:
# Random Function

In [126]:
np.random.rand(3,4)

array([[0.21628229, 0.35446862, 0.1348908 , 0.29177549],
       [0.53074825, 0.96903994, 0.10085751, 0.9240247 ],
       [0.4836997 , 0.54541238, 0.03174346, 0.40199365]])

In [127]:
arr = np.random.randn(3,4)

In [128]:
import pandas as pd 

In [129]:
pd.DataFrame(arr)

0         1         2         3
0 -1.210416  0.116891  0.158123 -1.829267
1  0.383100 -0.073480  0.456869 -1.663412
2 -1.085035  0.194122  1.295014 -1.288656

In [130]:
np.random.rand(3,4)

array([[0.0870609 , 0.15586629, 0.56691428, 0.41168834],
       [0.76556209, 0.22701124, 0.43076889, 0.17069736],
       [0.26241057, 0.47820566, 0.19164431, 0.29677693]])

In [132]:
np.random.randint(1,110 , (300,400))

array([[ 72,  36,  55, ...,  36, 102, 103],
       [  1,   4,  80, ...,  47, 108,   4],
       [ 16,  62,  15, ...,  99,  15,  18],
       ...,
       [ 31,  29,  61, ...,  92,  74, 102],
       [ 73,   7, 109, ..., 103,  32,  11],
       [ 87,  40,  48, ...,  83,  93,  21]])

In [133]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     95   98   71   25   45   30   59   51   18   51  ...   67    5   92   
1     27   24   43   47   56   68    5   98   20   22  ...   92    8    9   
2    101   74   62   81   79   32   81   82   50    3  ...   91   84  103   
3     59   25   27   92   79   79  105   94   99   33  ...    1   47   84   
4     30    6   54  108   60   45   22   25   29   41  ...   31   70   46   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   12   13    9   86   52   22   42   45   76   64  ...   58   53  107   
296   54   96   28   69   84   85    7   48   31   56  ...   83   75   62   
297   94   23    5   45   22   93    5  106    5   47  ...   80   55   23   
298   89   47   11  106   42   86   53   24   34    6  ...   14   51  105   
299   10  109    7   40   51  101  108   16    8   60  ...   88  101   65   

     393  394  395  396  397  398  399  
0    106   42   72   83   83   11   32  
1     63   28  107   30   48   30  105  
2    109   60   93   80   30   42   59  
3     14   51   66  101   41   58  106  
4     29  105   28   45   90   25  104  
..   ...  ...  ...  ...  ...  ...  ...  
295   48   30   71   75    9  101    3  
296   24   60   76   94   57   95  101  
297   12   35   68   51   26  108   11  
298    8   51   59   16   11   82   19  
299   62   45  101   29   43   22   10  

[300 rows x 400 columns]

In [134]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv("test.csv")

In [135]:
arr = np.random.rand(3,4)

In [136]:
arr

array([[0.21006783, 0.77130394, 0.47500338, 0.78181857],
       [0.84402228, 0.42854173, 0.76951427, 0.9585058 ],
       [0.23861384, 0.45876288, 0.46016994, 0.8281951 ]])

In [139]:
arr1=arr.reshape(6,2)

In [140]:
arr1

array([[0.21006783, 0.77130394],
       [0.47500338, 0.78181857],
       [0.84402228, 0.42854173],
       [0.76951427, 0.9585058 ],
       [0.23861384, 0.45876288],
       [0.46016994, 0.8281951 ]])

In [141]:
arr1[1] 

array([0.47500338, 0.78181857])

In [142]:
arr1[1] [1]

0.7818185666413576

In [147]:
arr1[2:5,1]

array([0.42854173, 0.9585058 , 0.45876288])

In [151]:
arr = np.random.randint(1,100 ,(5,5))

In [152]:
arr

array([[19, 81, 97, 85, 37],
       [90, 79,  4, 97,  9],
       [36, 51, 76, 98,  5],
       [ 5, 62, 54, 28, 42],
       [88, 39, 75, 80, 82]])

In [154]:
arr[arr>50]

array([81, 97, 85, 90, 79, 97, 51, 76, 98, 62, 54, 88, 75, 80, 82])

In [155]:
arr

array([[19, 81, 97, 85, 37],
       [90, 79,  4, 97,  9],
       [36, 51, 76, 98,  5],
       [ 5, 62, 54, 28, 42],
       [88, 39, 75, 80, 82]])

In [160]:
arr[2:4 , [1,2]]

array([[51, 76],
       [62, 54]])

In [162]:
arr[2:4 , [3,4]]

array([[98,  5],
       [28, 42]])

In [164]:
arr[3:5 ,[2,3]]

array([[54, 28],
       [75, 80]])

In [165]:
arr[0][0] = 5000

In [166]:
arr1 = np.random.randint(1,3 ,(3,3))
arr2 = np.random.randint(1,3 ,(3,3))

In [167]:
arr1

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [168]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [171]:
arr1+arr2

array([[3, 3, 3],
       [2, 3, 3],
       [3, 2, 3]])

In [172]:
arr1*arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 1, 2]])

In [175]:
arr1

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [176]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [177]:
arr1/0

/tmp/ipykernel_165/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [179]:
arr1 +100

array([[102, 101, 101],
       [101, 101, 101],
       [102, 101, 101]])

In [180]:
arr1**2

array([[4, 1, 1],
       [1, 1, 1],
       [4, 1, 1]])

In [182]:
row = np.array([1,2,3,4,5])

In [183]:
row

array([1, 2, 3, 4, 5])

In [184]:
arr * row

array([[5000,  162,  291,  340,  185],
       [  90,  158,   12,  388,   45],
       [  36,  102,  228,  392,   25],
       [   5,  124,  162,  112,  210],
       [  88,   78,  225,  320,  410]])

In [185]:
row.T

array([1, 2, 3, 4, 5])

In [186]:
col = np.array([[1,2,3,4]])

In [193]:
col

array([[1, 2, 3, 4]])

In [194]:
arr

array([[5000,   81,   97,   85,   37],
       [  90,   79,    4,   97,    9],
       [  36,   51,   76,   98,    5],
       [   5,   62,   54,   28,   42],
       [  88,   39,   75,   80,   82]])

In [196]:
arr1 = np.random.randint(1,4 , (3,4))

In [197]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.        , 1.41421356],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.        , 1.        , 1.73205081, 1.41421356]])

In [198]:
np.exp(arr1)

array([[20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [20.08553692, 20.08553692,  7.3890561 , 20.08553692],
       [ 2.71828183,  2.71828183, 20.08553692,  7.3890561 ]])

In [199]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.        , 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   , 0.47712125],
       [0.        , 0.        , 0.47712125, 0.30103   ]])